version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - soc-network

  server:
    build: ./server
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/cybershield
      - REDIS_URL=redis://redis:6379
      - AI_ENGINE_URL=http://ai-engine:5001
      - JWT_SECRET=supersecretSOCkey123
    depends_on:
      - mongo
      - redis
      - ai-engine
    networks:
      - soc-network

  ai-engine:
    build: ./ai-engine
    ports:
      - "5001:5001"
    networks:
      - soc-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - soc-network

  redis:
    image: redis:alpine
    networks:
      - soc-network

networks:
  soc-network:
    driver: bridge

volumes:
  mongo-data:
